<?php
$designId 	= $block->getDesignId();
$apiKey 	= $block->getApiKey();

?>

<?php if ( $designId && $designId != 'none' && $apiKey ) : ?>

	<input type="hidden" id="_pitchprint" name="_pitchprint"/>
	
	<script defer="true" src="https://pitchprint.io/rsc/js/client.js"></script>

	<div id="pp_main_btn_sec"></div>

	<script>

		function pp_w2p_getProductId() {
			const productSel = document.querySelector('#product_addtocart_form input[name=product]');
			return productSel ? productSel.value : 0;
		}
		
		function pp_w2p_getLocalPId(productId) {
			if (!localStorage.hasOwnProperty('pp_w2p_projects'))
				return 0;
			const _data = JSON.parse(localStorage.pp_w2p_projects)[productId];
			if (_data) return _data.projectId;
			return 0;
		}
		
		(function( _doc, window, require ) {

			require(['jquery', 'domReady!'], function () 
			{
				const productId = pp_w2p_getProductId();
				const localPId = pp_w2p_getLocalPId(productId);
				
				if (typeof PitchPrintClient === 'undefined') return;

				window.ppclient = new PitchPrintClient({
					uploadUrl: 'url_pending',
					userId: '1',
					langCode: 'en',
					enableUpload: 0,
					designId: '<?=$designId?>',
					previews: '',
					mode: localPId ? 'edit': 'new',
					createButtons: true,
					projectId: localPId,
					pluginRoot: 'path_pending',
					apiKey: '<?=$apiKey?>',
					client: 'mg',
					product: {
						id: productId,
						name: '' // todo get product name
					},
					userData: {
						email: '',
						name: '',
						firstname: '',
						lastname: '',
						telephone: '',
						address: ''
					}
				});
				require(['PitchPrintOnProductLoad', 'PitchPrintAfterSave', 'PitchPrintAfterAddCart']);
			});
		})(document, window, require);
	</script>

<?php endif; ?>