<?php $_item = $block->getItem() ?>
<?php $block->setPriceDataObject($_item) ?>
<tr>
    <?php $i = 0;
    $columns = $block->getColumns();
    $lastItemNumber = count($columns) ?>
    <?php foreach ($columns as $columnName => $columnClass):?>
        <?php $i++; ?>
        <td class="<?= $columnClass ?><?=  ($i === $lastItemNumber ? ' last' : '') ?>"><?= $block->getColumnHtml($_item, $columnName) ?>
    	<?php if ($i === 1) : ?>
            <?php $ppId = $block->fetchPpData(); ?>
            <?php if ($ppId) : ?>
                <span style="display:none" id="_pitchprint-data_<?=$ppId?>" value="<?=$ppId?>"></span>
            <?php endif; ?>
        <?php endif; ?>
        </td>
    <?php endforeach; ?>
</tr>
