<?php
	/* 
     * PitchPrint Admin JS for Magento 
     *
     * @ Magento v2.3
     * @ PitchPrint v9
     *
     */
?>

<script>  
(function( _doc, window, require ) {
    require(['jquery', 'domReady!'], function () 
    {
        const   baseUrl = 'https://pitchprint.io',
                pdfUrl  = 'https://pdf.pitchprint.com',
                adminBase = 'https://admin.pitchprint.com';
                
        jQuery('[id^=_pitchprint-data]').each(genLinks);
        
        function genLinks() {
            const parentTBody   = jQuery(this).closest('tbody');
            const pData         = JSON.parse(decodeURIComponent(this.getAttribute('id').replace('_pitchprint-data_','')));
            const pId           = pData.projectId;
            
            let _html = `<tr>
                            <td>
                                <img src="${baseUrl}/previews/${pId}_1.jpg" width="50px">
                            </td>
                            <td>
                                &#8226; <a target="_blank" href="${pdfUrl}/${pId}">Download PDF File</a>
                                <br/>&#8226; <a target="_blank" href="${pdfUrl}?id=${pId}&raster=1" >Download Raster Renderings</a>
                                <br/>&#8226; <a target="_blank" href="${adminBase}/projects#${pId}">Load Project and Modify</a>
                            </td>
                        </tr>`;
                        
            parentTBody.append(_html);
        }
    });
})(document, window, require);
</script>