<?php 
    $saveUrl = $this->helper('Magento\Backend\Helper\Data')->getUrl('pitchprint/configuration/save');
    $myData = $this->getName();
?>

<form class="form" action="<?=$saveUrl?>" method="post">
    
    <div style="margin-left: 10px; border: 1px solid #cccccc; border-radius: 6px; width: 50%; padding: 10px; margin-bottom: 10px">
        
        <div style="display: inline-block; margin-right: 12%">
            <div style="margin-bottom:16%">
                <label>API Key:</label>
            </div>
            <div>
                <label>Secrete Key:</label>
            </div>
        </div>

        <div style="display:inline-block">
            <div>
                <input style="margin-bottom:5%; width:180%" type="text" name="api_key" value="<?=$myData['api_key']?>">				
            </div>
            <div>
                <input style="width:180%" type="text" name="secret_key" value="<?=$myData['secret_key']?>">
            </div>
        </div>  
        
    </div>

    <div style="margin-left: 45%">
        <input type="submit" value="Save"> 
    </div>
    
</form>